# See https://redocly.com/docs/cli/configuration/ for more information.
apis:
  sample@v1: 
    root: openapi/Attendance-v1.json
  sample@v2: 
    root: openapi/Attendance-v2.json
lint:
  extends:
    - recommended
  rules:
    no-unused-components: error
features.openapi:
  showConsole: false
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#32329f"
