openapi: 3.1.0
info:
  version: 1.0.0
  title: Swagger UKG
  termsOfService: 'https://ukg.com/terms/'
  contact:
    name: API Support
    email: contact@ukg.com
    url: 'http://ukg.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://redocly.github.io/redoc/ukg-logo.png'
    altText: UKG logo
  description:
    $ref: ./info-description.md
tags:
  - name: Attendance
    description: Operations about attendance.
  - name: Platform
    description: Operations about platform.
  - name: Scheduling
    description: This is a scheduling description.
  - name: Timekeeping
    description: This is a timekeeping description.
servers:
  - url: 'https://{tenant}/api/v1'
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: 'https://ukg.com/api/v1'
paths:
  '/users/{username}':
    $ref: 'paths/users_{username}.yaml'
  /echo:
    $ref: paths/echo.yaml
  /pathItem:
    $ref: paths/path-item.yaml
  /pathItemWithExamples:
    $ref: paths/path-item-with-examples.yaml
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
