openapi: 3.1.0
info:
  version: 1.0.0
  title: Swagger UKG
  termsOfService: 'https://ukg.com/terms/'
  contact:
    name: API Support
    email: contact@ukg.com
    url: 'http://ukg.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://redocly.github.io/redoc/ukg-logo.png'
    altText: UKG logo
  description:
    $ref: ./info-description.md
tags:
  - name: Attendance
  - name: Common Resources I
  - name: Common Resources II
  - name: Scheduling
  - name: Timekeeping
  - name: Important notes
  - name: Authentication
  - name: Version History
x-tagGroups:
  - name: API
    tags:
      - Attendance
      - Common Resources I
      - Common Resources II
      - Scheduling
      - Timekeeping
    
  - name: Docs
    tags:
      - Important notes
      - Authentication
      - Version History
servers:
  - url: 'https://{tenant}/api/v1'
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: 'https://ukg.com/api/v1'
paths:
  /v1/attendance/actions/complete:
    $ref: paths/attendance-actions-complete.yaml
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
