openapi: 3.1.0
info:
  version: 1.0.0
  title: Swagger UKG
  termsOfService: 'https://ukg.com/terms/'
  contact:
    name: API Support
    email: contact@ukg.com
    url: 'http://ukg.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://redocly.github.io/redoc/ukg-logo.png'
    altText: UKG logo
  description:
    $ref: ./info-description.md
tags:
  - name: Attendance
  - name: Common Resources I
  - name: Common Resources II
  - name: Scheduling
  - name: Timekeeping
  - name: Important notes
  - name: Authentication
  - name: Version History
x-tagGroups:
  - name: API
    tags:
      - Attendance
      - Common Resources I
      - Common Resources II
      - Scheduling
      - Timekeeping
  - name: Docs
    tags:
      - Important notes
      - Authentication
      - Version History
servers:
  - url: 'https://{tenant}/api/v1'
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: 'https://ukg.com/api/v1'
paths:
  /v1/attendance/actions/complete:
    $ref: paths/attendance-actions-complete.yaml
  /v1/attendance/actions/documents/multi_read:
    $ref: paths/attendance-actions-documents-multi-read.yaml
  /v1/attendance/actions/multi_read:
    $ref: paths/attendance-actions-multi-read.yaml
  /v1/attendance/actions/{id}:
    $ref: paths/attendance-actions-id.yaml
components:
  schemas:
    CompleteActionsRequestContext:
      type: object
      description: Request Context object for action completion.
      properties:
        completionDateTime:
          type: string
          description: Date of completion.
        dateRange:
          $ref: "#/components/schemas/AttendanceDateRange"
          description: The date range, which contains a start date, an end date, and a symbolic period. The symbolic period reference is mutually exclusive with start date and end date.
        employees:
          $ref: "#/components/schemas/ObjectReferenceList"
          description: A list of references to employee objects.
        note:
          type: string
          description: User Note.
      required:
        - completionDateTime
        - dateRange
        - employees
        - note
    AttendanceDateRange:
      type: object
      description: The date range with symbolic period model.
      properties:
        startDate:
          type: string
          description: The start date of a date range in ISO_LOCAL_DATE format (YYYY-MM-DD).
        endDate:
          type: string
          description: The end date of a date range in ISO_LOCAL_DATE format (YYYY-MM-DD).
        symbolicPeriod:
          $ref: "#/components/schemas/AttendanceObjectReferenceDto"
          description: A reference to a symbolic period object.
      required:
        - startDate
        - endDate
        - symbolicPeriod
    AttendanceObjectReferenceDto:
      type: object
      description: The leave object reference model.
      properties:
        id:
          type: integer
          description: The ID of a leave domain entity.
          format: int64
        qualifier:
          type: string
          description: The qualifier which resolves an object reference.
      required:
        - qualifier
    ObjectReferenceList:
      type: object
      description: A list of object reference objects.
      properties:
        ids:
          type: array
          description: A list of IDs.
          items:
            type: integer
            format: int64
        qualifier:
          type: array
          description: A list of qualifiers.
          items:
            type: string
        refs:
          type: array
          description: A list of reference objects. Reference objects contain ID and qualifier.
          items:
            $ref: "#/components/schemas/AttendanceObjectReferenceDto"
      required:
        - ids
        - qualifiers
        - refs
    
